### ISSUE TITLE
Move metavaults packages to public npm

### ISSUE THREAD

**Issue by naddison36** [mstable/metavaults#76]
Now that the metavaults repo is public, the packages can also be moved to a npm.
This applies for both the server-side and frontend packages published from the metavaults repository.

This should include changing the Defender repo to use the new public npm package.

**Comment by doncesarts** [comment]
@toniocodo   you might be impacted by this

**Comment by doncesarts** [comment]
NPM Packages published https://www.npmjs.com/package/@mstable/metavaults
